server:
  port: 8083  # Порт, на котором будет работать приложение

spring:
  application:
    name: order-service  # Имя приложения
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    show-sql: true  # Показать SQL-запросы в логе
    properties:
      hibernate.format_sql: true  # Форматировать SQL для лучшей читаемости
      hibernate.type: true
      hibernate.use_sql_comments: true

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE

retryabletask:
  limit: 100
  timeoutInSeconds: 36000

integration:
  deliveryService:
    url: ${DELIVERY_SERVICE_URL:http://localhost:8081/api/v1}
  notificationService:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8082/api/v1}
